CREATE DATABASE WMS

GO
USE WMS
GO

CREATE TABLE Models
(
	ModelId INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Mechanics
(
	MechanicId  INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Address NVARCHAR(255) NOT NULL
)

CREATE TABLE Clients
(
	ClientId INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL
)

CREATE TABLE Jobs
(
	JobId INT PRIMARY KEY IDENTITY NOT NULL,
	ModelId INT FOREIGN KEY REFERENCES Models(ModelId) NOT NULL,
	Status NVARCHAR(11) NOT NULL DEFAULT('Pending') CHECK(Status = 'Pending' OR Status = 'In Progress' OR Status = 'Finished'),
	ClientId  INT FOREIGN KEY REFERENCES Clients(ClientId) NOT NULL,
	MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
	IssueDate DATE NOT NULL,
	FinishDate  DATE 
)

CREATE TABLE Orders
(
	OrderId INT PRIMARY KEY IDENTITY NOT NULL,
	JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
	IssueDate DATE,
	Delivered BIT NOT NULL
)

CREATE TABLE Vendors
(
	VendorId INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Parts
(
	PartId INT PRIMARY KEY IDENTITY NOT NULL,
	SerialNumber NVARCHAR(50) UNIQUE NOT NULL,
	Description NVARCHAR(255),
	Price DECIMAL(6, 2) CHECK(Price > 0) NOT NULL,
	VendorId INT FOREIGN KEY REFERENCES Vendors(VendorId) NOT NULL,
	StockQty INT DEFAULT(0) NOT NULL, CHECK(StockQty >= 0) 
)

CREATE TABLE PartsNeeded
(
	JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
	PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
	Quantity INT DEFAULT(1) NOT NULL, CHECK(Quantity > 0),
	CONSTRAINT PK_JobsParts PRIMARY KEY (JobId,PartId)  
)

CREATE TABLE OrderParts
(
	OrderId INT FOREIGN KEY REFERENCES Orders(OrderId) NOT NULL,
	PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
	Quantity INT DEFAULT(1) NOT NULL, CHECK(Quantity > 0),
	CONSTRAINT PK_OrderParts PRIMARY KEY (OrderId, PartId) 
)




